### PR TITLE
Make the library portable and upgrade to .NET 4.6 / Visual Studio 2015

### PR DESCRIPTION
**Pull request by ApocalypticOctopus**
Unfortunately the `IsAssignableFrom` method is not available for .NET 4.5 (or 4.5.1) Portable Class Libraries.

To make CSharpMonad be a portable class library, we'll have to upgrade it to .NET 4.6 and a minimum of Visual Studio 2015. The advantage is that this library will be available for all Windows Universal 10 apps (which includes all the platforms listed [here](https://msdn.microsoft.com/library/windows/apps/dn894631.aspx?f=255&MSPPError=-2147217396#device_families)); the disadvantage is that the library wouldn't be available to code using less than .NET 4.6.

What do you think--is this tradeoff acceptable?

### CODE REVIEW

**Comment by louthy** [comment]
You can use `Type.GetTypeInfo().IsAssignableFrom(...)`, I had to do that for my `language-ext` project when I made it support `dnxcore50`, `net45`, `net46`, dnx451` and `dnx461`.  

`GetTypeInfo` is an extension method, you must be `using System.Reflection`.  

Just had a quick flick through the changes.  What's the `string` / `IEnumerable<char>` stuff about?  Do you have a reference to why that's necessary?  It seems a bit 'odd'.  Sorry I don't have much time to dig into it myself right now, super busy with other projects...

To be honest I'd rather do the work to make this use `project.json` and build that way than modify the existing sln/csproj.  Primarily because it automatically builds all of the artifacts needed to push to nuget, and supports multiple frameworks.  

I have been putting it off after the horror experience of migrating `language-ext`.  Well, I say _after_, it's still in progress - that's weeks of my life I won't get back!).  Still, it seems to currently be the best route to getting DLLs that can be used in W10 (as well as cross platform).

**Comment by ApocalypticOctopus** [comment]
Thanks for the tip, that fixed the issue! The pull request now depends on .NET 4.5.

No worries! [Here](http://stackoverflow.com/questions/11521675/string-intern-method-missing-in-metro-c-sharp/11522718#11522718) is a Stackoverflow answer describing the `string` / `IEnumerable<char>` stuff.

If I understand you correctly, you're saying that you would rather modify the existing project than re-create it as a portable class library project, because the original project file had some really convenient features. I can look into doing that instead but I'm not familiar with that way of doing things (I'm pretty new to all this Windows Universal stuff), so I probably won't be able to actually make those changes for quite a while.

In any case, I don't want to put pressure on you to merge the pull request. Do whatever is best for you, don't stress out about it please.

**Comment by louthy** [comment]
@ApocalypticOctopus - Just to let you know, I haven't forgotten!  Still in the midst of a big roll-out at work, so my OS work is on the back burner atm.

**Comment by ApocalypticOctopus** [comment]
@louthy Thanks for the info! I totally understand.

**Comment by louthy** [comment]
@ApocalypticOctopus Sorry, I had forgot.  Merged now ;)

**Comment by ApocalypticOctopus** [comment]
No worries, thank you! :+1:

**Pull request merged**
